Fix compiler error with JIT when EXT_M is disabled
When using 'make ENABLE_EXT_M=0 ENABLE_JIT=1', the following error is
observed:

src/jit.c:1693:13: error: ‘ra_load2_sext’ defined but not used [-Werror=unused-function]
 1693 | static void ra_load2_sext(struct jit_state *state,
      |             ^~~~~~~~~~~~~

Fix this by guarding the ra_load2_sext function definition with
RV32_HAS(EXT_M) macro. This ensures the function is only defined when
the M extension is enabled.