Fix Clang error when disabling MOP FUSION
When using 'make ENABLE_MOP_FUSION=0 CC=clang', the following error is
observed:
src/emulate.c:695:20: error: unused function 'remove_next_nth_ir' [-Werror,-Wunused-function]
  695 | static inline void remove_next_nth_ir(const riscv_t *rv,
	  |                    ^~~~~~~~~~~~~~~~~~
1 error generated.

Fix this by guarding the remove_next_nth_ir function definition with
RV32_HAS(MOP_FUSION) macro. This ensures the function is only defined
when the MOP_FUSION is enabled.