Fix Clang error with JIT when EXT_C is disabled
When using 'make make ENABLE_EXT_C=0 ENABLE_JIT=1 CC=clang', the
following errors are observed:

rc/t2c.c:77:1: error: unused function 't2c_gen_ra_addr' [-Werror,-Wunused-function]
   77 | T2C_LLVM_GEN_ADDR(ra, X, rv_reg_ra);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/t2c.c:64:31: note: expanded from macro 'T2C_LLVM_GEN_ADDR'
   64 |     FORCE_INLINE LLVMValueRef t2c_gen_##reg##_addr(                           \
      |                               ^~~~~~~~~~~~~~~~~~~~
<scratch space>:75:1: note: expanded from here
   75 | t2c_gen_ra_addr
      | ^~~~~~~~~~~~~~~
src/t2c.c:78:1: error: unused function 't2c_gen_sp_addr' [-Werror,-Wunused-function]
   78 | T2C_LLVM_GEN_ADDR(sp, X, rv_reg_sp);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/t2c.c:64:31: note: expanded from macro 'T2C_LLVM_GEN_ADDR'
   64 |     FORCE_INLINE LLVMValueRef t2c_gen_##reg##_addr(                           \
      |                               ^~~~~~~~~~~~~~~~~~~~

Fix this by guarding the 't2c_gen_ra_addr' and 't2c_gen_sp_addr'
function definition with RV32_HAS(EXT_C) macro. This ensures the
functions are only defined when the EXT_C is enabled.