Fix undeclared identifier 'attr' error
Building with 'ENABLE_JIT=1, ENABLE_SYSTEM=1, and ENABLE_ELF_LOADER=0'
causes the following errors:
src/riscv.c:582:18: error: use of undeclared identifier 'attr'
  582 |     u8250_delete(attr->uart);
      |                  ^
src/riscv.c:583:17: error: use of undeclared identifier 'attr'
  583 |     plic_delete(attr->plic);
      |                 ^

These errors occur because attr is not defined under these conditions.
Fix this by adjusting the guard for attr to
(RV32_HAS(SYSTEM) && !RV32_HAS(ELF_LOADER)), ensuring it is defined as
needed.