Fix compiler errors with JIT when Zbb is disabled
When using 'make ENABLE_Zbb=0 ENABLE_JIT=1', the following errors are
observed:

src/jit.c:1760:17: error: ‘do_rev8’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_orcb’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_rori’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_ror’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_rol’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_zexth’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_sexth’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_sextb’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_minu’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_maxu’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_min’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_max’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_cpop’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_ctz’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_clz’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_xnor’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_orn’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_andn’ defined but not used [-Werror=unused-function]

Include 'Zbb' in EXT_LIST to ensure instructions like 'rev8',
'orcb', and 'rori' are properly handled, resolving unused function
errors during JIT builds.